package kittoku.mvc.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverter
import androidx.room.TypeConverters
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * VPN connection profile entity.
 *
 * Represents a saved VPN connection configuration that can be stored in the database
 * and exported/imported as JSON.
 *
 * @property id Unique identifier for the profile (auto-generated by Room)
 * @property name User-friendly name for the profile
 * @property serverAddress VPN server hostname or IP address
 * @property username Username for authentication
 * @property port Server port (default: 443 for HTTPS)
 * @property hubName SoftEther VPN hub name (default: "DEFAULT")
 * @property password Password for authentication (not exported by default)
 * @property useTls Whether to use TLS encryption
 * @property verifyServerCertificate Whether to verify the server's SSL certificate
 * @property autoConnect Whether to auto-connect when the app starts
 * @property autoConnectOnWifi Whether to auto-connect when WiFi is available
 * @property autoConnectOnMobile Whether to auto-connect on mobile data
 * @property splitTunneling Whether split tunneling is enabled
 * @property excludedApps List of app package names to exclude from VPN
 * @property includedApps List of app package names to route through VPN only
 * @property customDns Custom DNS server address (null for default)
 * @property createdAt Timestamp when the profile was created
 * @property updatedAt Timestamp when the profile was last updated
 */
@Entity(tableName = "vpn_profiles")
@TypeConverters(StringListConverter::class)
@Serializable
data class VpnProfile(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val name: String,
    val serverAddress: String,
    val username: String,
    val port: Int = DEFAULT_PORT,
    val hubName: String = DEFAULT_HUB_NAME,
    @Transient
    val password: String = "",
    val useTls: Boolean = true,
    val verifyServerCertificate: Boolean = true,
    val autoConnect: Boolean = false,
    val autoConnectOnWifi: Boolean = false,
    val autoConnectOnMobile: Boolean = false,
    val splitTunneling: Boolean = false,
    val excludedApps: List<String> = emptyList(),
    val includedApps: List<String> = emptyList(),
    val customDns: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
) {
    companion object {
        const val DEFAULT_PORT = 443
        const val DEFAULT_HUB_NAME = "DEFAULT"
        private const val MIN_PORT = 1
        private const val MAX_PORT = 65535

        private val exportJson =
            Json {
                prettyPrint = true
                ignoreUnknownKeys = true
                encodeDefaults = true
            }
    }

    /**
     * Validates the profile and returns true if all required fields are valid.
     */
    fun isValid(): Boolean = validationErrors().isEmpty()

    /**
     * Returns a list of validation error messages.
     * Empty list means the profile is valid.
     */
    fun validationErrors(): List<String> {
        val errors = mutableListOf<String>()

        if (name.isBlank()) {
            errors.add("Name cannot be blank")
        }

        if (serverAddress.isBlank()) {
            errors.add("Server address cannot be blank")
        }

        if (username.isBlank()) {
            errors.add("Username cannot be blank")
        }

        if (port !in MIN_PORT..MAX_PORT) {
            errors.add("Port must be between $MIN_PORT and $MAX_PORT")
        }

        return errors
    }

    /**
     * Creates a copy of this profile with an updated timestamp.
     */
    fun withUpdatedTimestamp(): VpnProfile =
        copy(
            updatedAt = System.currentTimeMillis(),
        )

    /**
     * Exports the profile to JSON format.
     *
     * @param includePassword Whether to include the password in the export (default: false)
     * @return JSON string representation of the profile
     */
    fun toExportJson(includePassword: Boolean = false): String {
        val exportProfile =
            if (includePassword) {
                ExportableProfile.fromVpnProfile(this, includePassword = true)
            } else {
                ExportableProfile.fromVpnProfile(this, includePassword = false)
            }
        return exportJson.encodeToString(exportProfile)
    }

    /**
     * Internal class for JSON export that controls password visibility.
     */
    @Serializable
    internal data class ExportableProfile(
        val id: Long,
        val name: String,
        val serverAddress: String,
        val username: String,
        val port: Int,
        val hubName: String,
        val password: String?,
        val useTls: Boolean,
        val verifyServerCertificate: Boolean,
        val autoConnect: Boolean,
        val autoConnectOnWifi: Boolean,
        val autoConnectOnMobile: Boolean,
        val splitTunneling: Boolean,
        val excludedApps: List<String>,
        val includedApps: List<String>,
        val customDns: String?,
        val createdAt: Long,
        val updatedAt: Long,
    ) {
        companion object {
            fun fromVpnProfile(
                profile: VpnProfile,
                includePassword: Boolean,
            ): ExportableProfile {
                return ExportableProfile(
                    id = profile.id,
                    name = profile.name,
                    serverAddress = profile.serverAddress,
                    username = profile.username,
                    port = profile.port,
                    hubName = profile.hubName,
                    password = if (includePassword) profile.password else null,
                    useTls = profile.useTls,
                    verifyServerCertificate = profile.verifyServerCertificate,
                    autoConnect = profile.autoConnect,
                    autoConnectOnWifi = profile.autoConnectOnWifi,
                    autoConnectOnMobile = profile.autoConnectOnMobile,
                    splitTunneling = profile.splitTunneling,
                    excludedApps = profile.excludedApps,
                    includedApps = profile.includedApps,
                    customDns = profile.customDns,
                    createdAt = profile.createdAt,
                    updatedAt = profile.updatedAt,
                )
            }
        }
    }
}

/**
 * Room TypeConverter for List<String> to store app package names.
 */
class StringListConverter {
    private val json = Json { ignoreUnknownKeys = true }

    @TypeConverter
    fun fromStringList(value: List<String>): String {
        return json.encodeToString(value)
    }

    @TypeConverter
    fun toStringList(value: String): List<String> {
        return if (value.isEmpty()) {
            emptyList()
        } else {
            json.decodeFromString(value)
        }
    }
}
