package kittoku.mvc.statistics

import com.google.common.truth.Truth.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import java.util.Locale

/**
 * TDD tests for ConnectionSession entity.
 *
 * ConnectionSession represents a completed VPN connection session
 * that is stored in the database for history and statistics.
 */
@DisplayName("ConnectionSession")
class ConnectionSessionTest {
    @Nested
    @DisplayName("Creation")
    inner class Creation {
        @Test
        @DisplayName("should create with required fields")
        fun shouldCreateWithRequiredFields() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 1000L,
                    endTime = 2000L,
                )

            assertThat(session.profileId).isEqualTo(1L)
            assertThat(session.serverAddress).isEqualTo("vpn.example.com")
            assertThat(session.startTime).isEqualTo(1000L)
            assertThat(session.endTime).isEqualTo(2000L)
        }

        @Test
        @DisplayName("should have auto-generated id of 0 by default")
        fun shouldHaveAutoGeneratedIdOfZeroByDefault() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 1000L,
                    endTime = 2000L,
                )

            assertThat(session.id).isEqualTo(0L)
        }

        @Test
        @DisplayName("should default traffic to zero")
        fun shouldDefaultTrafficToZero() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 1000L,
                    endTime = 2000L,
                )

            assertThat(session.bytesSent).isEqualTo(0L)
            assertThat(session.bytesReceived).isEqualTo(0L)
        }
    }

    @Nested
    @DisplayName("Duration calculation")
    inner class DurationCalculation {
        @Test
        @DisplayName("should calculate duration in milliseconds")
        fun shouldCalculateDurationInMilliseconds() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 1000L,
                    endTime = 6000L,
                )

            assertThat(session.durationMillis).isEqualTo(5000L)
        }

        @Test
        @DisplayName("should calculate duration in seconds")
        fun shouldCalculateDurationInSeconds() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 60_000L,
                )

            assertThat(session.durationSeconds).isEqualTo(60L)
        }

        @Test
        @DisplayName("should format duration as HH:MM:SS")
        fun shouldFormatDurationAsHhMmSs() {
            // 1 hour 30 minutes 45 seconds = 5445 seconds
            val durationMs = (1 * 3600 + 30 * 60 + 45) * 1000L
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = durationMs,
                )

            assertThat(session.getFormattedDuration()).isEqualTo("01:30:45")
        }
    }

    @Nested
    @DisplayName("Traffic calculation")
    inner class TrafficCalculation {
        @Test
        @DisplayName("should calculate total bytes")
        fun shouldCalculateTotalBytes() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    bytesSent = 500L,
                    bytesReceived = 1500L,
                )

            assertThat(session.totalBytes).isEqualTo(2000L)
        }

        @Test
        @DisplayName("should format bytes sent")
        fun shouldFormatBytesSent() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    bytesSent = 1024L * 1024L,
                )

            assertThat(session.getFormattedBytesSent()).isEqualTo("1.0 MB")
        }

        @Test
        @DisplayName("should format bytes received")
        fun shouldFormatBytesReceived() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    bytesReceived = 2L * 1024L * 1024L * 1024L,
                )

            assertThat(session.getFormattedBytesReceived()).isEqualTo("2.0 GB")
        }
    }

    @Nested
    @DisplayName("Status")
    inner class Status {
        @Test
        @DisplayName("should indicate successful connection")
        fun shouldIndicateSuccessfulConnection() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 60_000L,
                    wasSuccessful = true,
                )

            assertThat(session.wasSuccessful).isTrue()
        }

        @Test
        @DisplayName("should indicate failed connection")
        fun shouldIndicateFailedConnection() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    wasSuccessful = false,
                    errorMessage = "Connection timeout",
                )

            assertThat(session.wasSuccessful).isFalse()
            assertThat(session.errorMessage).isEqualTo("Connection timeout")
        }

        @Test
        @DisplayName("should indicate disconnection reason")
        fun shouldIndicateDisconnectionReason() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 60_000L,
                    disconnectReason = DisconnectReason.USER_REQUESTED,
                )

            assertThat(session.disconnectReason).isEqualTo(DisconnectReason.USER_REQUESTED)
        }
    }

    @Nested
    @DisplayName("Date formatting")
    inner class DateFormatting {
        @Test
        @DisplayName("should format start date")
        fun shouldFormatStartDate() {
            // January 15, 2026 at 10:30:00 UTC
            val timestamp = 1768486200000L
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = timestamp,
                    endTime = timestamp + 1000L,
                )

            val formatted = session.getFormattedStartDate(Locale.US)
            assertThat(formatted).isNotEmpty()
        }

        @Test
        @DisplayName("should format start time")
        fun shouldFormatStartTime() {
            val timestamp = 1768486200000L
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = timestamp,
                    endTime = timestamp + 1000L,
                )

            val formatted = session.getFormattedStartTime(Locale.US)
            assertThat(formatted).isNotEmpty()
        }
    }

    @Nested
    @DisplayName("Hub and protocol info")
    inner class HubAndProtocolInfo {
        @Test
        @DisplayName("should store hub name")
        fun shouldStoreHubName() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    hubName = "VPN_HUB",
                )

            assertThat(session.hubName).isEqualTo("VPN_HUB")
        }

        @Test
        @DisplayName("should store protocol type")
        fun shouldStoreProtocolType() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    protocol = "UDP",
                )

            assertThat(session.protocol).isEqualTo("UDP")
        }

        @Test
        @DisplayName("should store assigned IP")
        fun shouldStoreAssignedIp() {
            val session =
                ConnectionSession(
                    profileId = 1L,
                    serverAddress = "vpn.example.com",
                    startTime = 0L,
                    endTime = 1000L,
                    assignedIp = "10.0.0.5",
                )

            assertThat(session.assignedIp).isEqualTo("10.0.0.5")
        }
    }
}
